repos:

  - repo: https://github.com/asottile/yesqa
    rev: v1.2.3
    hooks:
      - id: yesqa

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.13'
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    - id: bandit
      args: ["--skip", "B101"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy

  - repo: https://github.com/fpgmaas/deptry.git
    rev: 0.12.0
    hooks:
      - id: deptry

  - repo: local
    hooks:
      - id: poetry-check
        name: poetry check
        entry: poetry
        language: system
        types: [python]
        files: poetry.lock
        args: [check]
        pass_filenames: false
        always_run: true
      - id: poetry-lock
        name: poetry lock
        entry: poetry
        language: system
        types: [python]
        files: poetry.lock
        args: [lock]
        pass_filenames: false
        always_run: true
