site_name: "Eventiq"
site_description: Cloud native framework for building event driven applications in Python.
theme:
  favicon: "./assets/favicon.svg"
  logo: "./assets/favicon.svg"
  name: "material"
  palette:
  - scheme: default
    primary: cyan
    accent: teal
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  - scheme: slate
    primary: cyan
    accent: teal
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to light mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
repo_name: performancemedia/eventiq
repo_url: https://github.com/performancemedia/eventiq
nav:
  - "Eventiq": index.md
  - "Installation": installation.md
  - "Features": features.md
  - "Usage": usage.md
  - "Service": service.md
  - "Consumers": consumers.md
  - "Middlewares": middlewares.md
  - "HTTP": http.md
  - "AsyncAPI": async_api.md
  - "Changelog": changelog.md
  - "Examples":
      - "Basic": examples/base.md
      - "AsyncAPI": examples/asyncapi.md
      - "Generic Consumer": examples/generic_consumer.md
      - "Prometheus": examples/prometheus.md
      - "Fast API": examples/web.md
  - "Reference":
      - "Backends": reference/backends.md
      - "Consumers": reference/consumers.md
      - "Encoders": reference/encoders.md
      - "Exceptions": reference/exceptions.md
      - "Middlewares": reference/middlewares.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_signature_annotations: true
            docstring_style: sphinx
