brokers:
  default:
    type: eventiq.backends.nats:JetStreamBroker
    url: {EVENTIQ_BROKER_URL}
    encoder:
      type: eventiq.encoders.orjson:OrjsonEncoder
    middlewares:
      - type: eventiq.middlewares.retries:RetryMiddleware
  TEST:
    type: eventiq.backends.stub:StubBroker
    encoder:
      type: eventiq.encoders.orjson:OrjsonEncoder
    middlewares:
      - type: eventiq.middlewares.retries:RetryMiddleware
  PROD:
    type: eventiq.backends.nats:JetStreamBroker
    url: {EVENTIQ_BROKER_URL}
    encoder:
      type: eventiq.encoders.orjson:OrjsonEncoder
    middlewares:
      - type: eventiq.middlewares.retries:RetryMiddleware
      - type: eventiq.middlewares.prometheus:PrometheusMiddleware
        run_server: true
      - type: eventiq.middlewares.opentelemetry.OpentelemetryMiddleware
        tracer:
          type: app.tracing:tracer
services:
  - name: example-service
    version: 0.1.0
    broker: {ENV}
    consumers:
      - name: "consumer-1"
        type: app.consumers:consumer_1
        topic: "test.topic1"
        timeout: 120
        retry_strategy:
          type: eventiq.middlewares.retries:MaxAge
          max_age:
            hours: 2
      - name: "consumer-2"
        type: app.consumers:consumer_2
        topic: "test.topic2"
        timeout: 240
        retry_strategy:
          type: eventiq.middlewares.retries:MaxAge
          max_age:
            hours: 6
