name: docs
on:
  push:
    branches:
      - master
      - main
      - feat/docs-page
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: sudo apt-get update && sudo apt-get install -y curl
      - run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 -
      - run: poetry install
      - run: poetry run mkdocs gh-deploy --force