name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Build distribution
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.8.12
        with:
          password: ${{ secrets.PYPI_TOKEN }}